#!/usr/local/bin/perl
#  Copyright 2014, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id$
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CM

$GHRSST_PERL_LIB_DIRECTORY = $ENV{GHRSST_PERL_LIB_DIRECTORY};

do "$GHRSST_PERL_LIB_DIRECTORY/log_this.pl";
do "$GHRSST_PERL_LIB_DIRECTORY/mkdir_with_error_handling.pl";
do "$GHRSST_PERL_LIB_DIRECTORY/file_move_with_error_handling.pl";
do "$GHRSST_PERL_LIB_DIRECTORY/move_to_holding_tank_with_error_handling.pl";
do "$GHRSST_PERL_LIB_DIRECTORY/raise_sigevent.pl";

#------------------------------------------------------------------------------------------------------------------------
sub clean_up {
    # Do clean up.  Remove the SST working file if it exist and the combine was successful.  For SST4 and LAC_OC, we move them to holding tank
    # in case another version of the SST shows up later.

    my $i_file_created_successfully_flag = shift;
    my $i_sst_filename  = shift;
    my $i_sst4_filename = shift;
    my $i_oc_filename   = shift;
    my $i_scratch_area  = shift;
    my $i_processing_type = shift;
    my $i_original_sst_filename = shift;

    my $g_routine_name = "clean_up";

    if (($i_file_created_successfully_flag == 1) && (-e $i_sst_filename)) {
        if ($i_processing_type eq "AQUA_REFINED" || ($i_processing_type eq "TERRA_REFINED") || ($i_processing_type eq "VIIRS_REFINED")) {
            log_this("INFO",$g_routine_name,"REMOVING_FILE " .  $i_sst_filename);
            unlink ($i_sst_filename);
        } else {
            log_this("INFO",$g_routine_name,"KEEPING_QUICKLOOK_FILE_INPUT " .  $i_sst_filename);
            rename($i_sst_filename,$i_original_sst_filename);
            if (-e $i_original_sst_filename) {
              log_this("INFO",$g_routine_name,"MOVING_QUICKLOOK_FILE_TO_INPUT " . $i_sst_filename . " " .  $i_original_sst_filename);
            } else {
                $sigevent_msg = "QUICKLOOK_FILE_MOVE_TO_INPUT_FAILED_CANNOT_PERFORM_RENAME $i_sst_filename $i_original_sst_filename";
                log_this("ERROR",$g_routine_name,$sigevent_msg);
            }
        }
        
    } else {
        # Since we were not successful in combine the input file, we need to move it to a quarantine directory for operator to inspect.

        # Create the directory if it does not exist yet.
        if (!(-e $i_scratch_area)) {
            my $status_mkdir = mkdir_with_error_handling($i_scratch_area);
            # The mkdir function returns true if successful and false if failed.
            # if ($status_mkdir == 0) { exit(0); }
        }

        my $quarantine_directory = "$i_scratch_area/quarantine";

        # Create the directory if it does not exist yet.
        if (!(-e $quarantine_directory)) {
            my $status_mkdir = mkdir_with_error_handling($quarantine_directory);
            # The mkdir function returns true if successful and false if failed.
            # if ($status_mkdir == 0) { exit(0); }
        }
        # Use the module File::Copy to do the move.
        if (-e $i_sst_filename) {
           move($i_sst_filename,$quarantine_directory);
           log_this("ERROR",$g_routine_name,"FILE_MOVE_TO_QUARANTINE $i_sst_filename $quarantine_directory");
        }
    }

    if (($g_holding_tank_move_flag == 1) && ($i_file_created_successfully_flag == 1)) {
        move_to_holding_tank_with_error_handling($i_sst4_filename,$i_scratch_area);
        print "INFO $g_routine_name SST4 FILE MOVED TO SCRATCH: $i_sst4_filename\n";
    } else {
        # Only remove the file if the combined was successful.
        if ((-e $i_sst4_filename) && ($i_file_created_successfully_flag == 1)) {
            log_this("INFO",$g_routine_name,"REMOVING_FILE " . $i_sst4_filename);
            unlink ($i_sst4_filename);
        } else {
            # Since we were not successful in combine the input file, we need to move it to a quarantine directory for operator to inspect.

            my $quarantine_directory = "$i_scratch_area/quarantine";

            # Create the directory if it does not exist yet.
            if (!(-e $quarantine_directory)) {
                my $status_mkdir = mkdir_with_error_handling($quarantine_directory);
                # The mkdir function returns true if successful and false if failed.
                # if ($status_mkdir == 0) { exit(0); }
            }
            # Use the module File::Copy to do the move.
            if (-e $i_sst4_filename) {
                move($i_sst4_filename,$quarantine_directory);
                log_this("ERROR",$g_routine_name,"FILE_MOVE_TO_QUARANTINE $i_sst4_filename $quarantine_directory");
            }
        }
    }
    if (($g_holding_tank_move_flag == 1) && ($i_file_created_successfully_flag == 1)) {
        move_to_holding_tank_with_error_handling($i_oc_filename,$i_scratch_area);
        print "INFO $g_routine_name OC FILE MOVED TO SCRATCH: $i_oc_filename\n";
    } else {
        # Only remove the file if the combined was successful.
        if ((-e $i_oc_filename) && ($i_file_created_successfully_flag == 1))  {
            log_this("INFO",$g_routine_name,"REMOVING_FILE " . $i_oc_filename);
            unlink ($i_oc_filename);
        } else {
            # Since we were not successful in combine the input file, we need to move it to a quarantine directory for operator to inspect.

            my $quarantine_directory = "$i_scratch_area/quarantine";

            # Create the directory if it does not exist yet.
            if (!(-e $quarantine_directory)) {
                my $status_mkdir = mkdir_with_error_handling($quarantine_directory);
                # The mkdir function returns true if successful and false if failed.
                if ($status_mkdir == 0) { exit(0); }
            }
            # Use the module File::Copy to do the move.
            if (-e $i_oc_filename) {
                move($i_oc_filename,$quarantine_directory);
                log_this("ERROR",$g_routine_name,"FILE_MOVE_TO_QUARANTINE $i_oc_filename $quarantine_directory");
            }
        }
    }

}

